# Mergify configuration for auto-merge after prow-github-actions adds labels
pull_request_rules:
  - name: Auto merge with prow labels
    conditions:
      - "label=lgtm"
      - "label=approved"
      - "check-success~=.*"
      - "-draft"
    actions:
      merge:
        method: squash