pull_request_rules:
  - name: Auto merge with labels
    conditions:
      - "label=lgtm"
      - "label=approved"
      - "check-success~=.*"
      - "-draft"
    actions:
      merge:
        method: squash