pull_request_rules:
  - name: Add lgtm label on /lgtm comment
    conditions:
      - "body~=/lgtm|comments~=/lgtm"
    actions:
      label:
        add:
          - "lgtm"

  - name: Add approved label on /approve comment  
    conditions:
      - "body~=/approve|comments~=/approve"
    actions:
      label:
        add:
          - "approved"

  - name: Automatic merge on /lgtm and /approve
    conditions:
      - "label=lgtm"
      - "label=approved"
      - "status-success~=.*"
      - "check-success~=.*"
      - "-draft"
      - "-conflict"
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          
          {{ body }}