apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: todoappbundle
  namespace: amcdermo-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
spec:
  application: todoapp
  componentName: todoappbundle
  containerImage: quay.io/redhat-user-workloads/amcdermo-tenant/todoapp/todoappbundle
  source:
    git:
      dockerfileUrl: bundle/Dockerfile
      url: https://github.com/frobware/sample-konflux-app
      revision: main