apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apps.todoapp.io/v1",
          "kind": "TodoApp",
          "metadata": {
            "name": "todoapp-sample"
          },
          "spec": {
            "image": "nginx:latest",
            "replicas": 1,
            "port": 8080
          }
        }
      ]
    capabilities: Basic Install
    categories: Application Runtime
    description: TodoApp operator manages simple todo application deployments
  name: todoapp-operator.v0.1.0
  namespace: todoapp
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TodoApp is the Schema for the todoapps API
      displayName: Todo App
      kind: TodoApp
      name: todoapps.apps.todoapp.io
      version: v1
  description: |
    The TodoApp operator manages simple todo application deployments in Kubernetes.
    It creates and manages Deployment and Service resources for TodoApp custom resources.
  displayName: TodoApp Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps.todoapp.io
          resources:
          - todoapps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps.todoapp.io
          resources:
          - todoapps/finalizers
          verbs:
          - update
        - apiGroups:
          - apps.todoapp.io
          resources:
          - todoapps/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: todoapp-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: sample-konflux-app
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: sample-konflux-app
          control-plane: controller-manager
        name: todoapp-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: todoapp-controller-manager
              terminationGracePeriodSeconds: 10
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - todoapp
  - operator
  - deployment
  links:
  - name: TodoApp Operator
    url: https://github.com/frobware/sample-konflux-app
  maintainers:
  - email: support@todoapp.io
    name: TodoApp Team
  maturity: alpha
  provider:
    name: TodoApp
  version: 0.1.0