# permissions for end users to edit todoapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sample-konflux-app
    app.kubernetes.io/managed-by: kustomize
  name: todoapp-editor-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - todoapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.example.com
  resources:
  - todoapps/status
  verbs:
  - get
