name: Prow Commands and Auto Merge

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  status: {}
  check_suite:
    types: [completed]

jobs:
  prow-commands:
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: jpmcb/prow-github-actions@v2
        with:
          prow-commands: '/lgtm /hold /cc /uncc /assign /unassign /kind /priority /area /milestone /close /reopen'
          github-token: '${{ secrets.GITHUB_TOKEN }}'

  remove-lgtm-on-update:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: jpmcb/prow-github-actions@v2
        with:
          jobs: lgtm
          github-token: '${{ secrets.GITHUB_TOKEN }}'

  auto-merge:
    if: >
      (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'lgtm') ||
      github.event_name == 'status' ||
      github.event_name == 'check_suite'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: jpmcb/prow-github-actions@v2
        with:
          jobs: lgtm
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          merge-method: squash